name: Integración Continua (CI) - Next.js a Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
      
      # CORRECCIÓN: Este paso faltaba. Es necesario para usar la caché avanzada.
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }} 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Definir Metadatos de Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: enmvnuel/expon.me
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Construir y Subir la Imagen a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # Ahora sí funcionará porque activamos Buildx arriba
          cache-from: type=gha 
          cache-to: type=gha,mode=max

      - name: Activar Despliegue en Dokploy
        env:
          DOKPLOY_WEBHOOK_URL: ${{ secrets.DOKPLOY_WEBHOOK_URL }}
        run: |
          echo "Imagen construida y subida."
          echo "Enviando webhook a Dokploy..."
          curl -X POST $DOKPLOY_WEBHOOK_URL
